In [9]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import warnings

# Ignore Deprecation Warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Using the Pandas library, read the "winemag-data-130k-v2.csv" into a variable named "wine_df"
wine_df = pd.read_csv("wine_data.csv")
    

# Using your "head", Print the top 5 rows of the dataframe
wine_df.head(5)

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

Identify the columns that do not have much impact on the wine quality. Drop the following column(s) from the dataframe: 'Unnamed: 0', 'designation', 'province', 'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'winery'. Assign the resulting matrix into a variable named "essential_wine_df"

In [10]:
essential_wine_df = wine_df.drop(['Unnamed: 0', 'designation', 'province', 'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'winery'],axis =1)


In [11]:
#print the top 5 data 
essential_wine_df.head()

country                                        description  points  price  \
0     Italy  Aromas include tropical fruit, broom, brimston...      87    NaN   
1  Portugal  This is ripe and fruity, a wine that is smooth...      87   15.0   
2        US  Tart and snappy, the flavors of lime flesh and...      87   14.0   
3        US  Pineapple rind, lemon pith and orange blossom ...      87   13.0   
4        US  Much like the regular bottling from 2012, this...      87   65.0   

                                               title         variety  
0                  Nicosia 2013 Vulkà Bianco  (Etna)     White Blend  
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  
2      Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris  
3  St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling  
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir

Filter the wine_df by column "variety" by the following values: 'Cabernet Sauvignon', 'Chardonnay', 'Merlot', 'Pinot Noir', 'White Riesling'. Assign the resulting dataframe into a variable dataframe named "essential_wine_df

In [12]:
essential_wine_df = essential_wine_df.loc[essential_wine_df['variety'].isin(['Cabernet Sauvignon', 'Chardonnay', 'Merlot', 'Pinot Noir', 'White Riesling'])]

In [13]:
essential_wine_df.head(5)
print(len(essential_wine_df))

37612


Remove any rows from the dataframe which contain a missing value (NaN). Assign the resulting matrix into a variable named "essential_wine_df"

In [14]:
essential_wine_df = essential_wine_df.dropna(axis = 0,how = 'any')

# Print the number of rows from the dataframe
print(len(essential_wine_df))

36320


Convert the 'price' column of the "essential_wine_df" to the datatype of 'int'

In [16]:
essential_wine_df['price'] = essential_wine_df['price'].astype(int)

# Print the data types of data from the clean_wine_filtered_by_variety_df dataframe
essential_wine_df.dtypes

country        object
description    object
points          int64
price           int32
title          object
variety        object
dtype: object

Convert the categorical variable into ohe encoded variable. The description contions some key words that describes the quality of the wine. We need a function to read the line and capture the words to get the columns of each features.

In [17]:
def conditional_column(dataframe, column, keyword):
    value1 = []
    for index,row in dataframe.iterrows():
        if keyword in row[column]:
            value = 1
        else:
            value = 0
        value1.append(value)
    return value1
    

In [18]:
essential_wine_df['vanilla'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="vanilla")
essential_wine_df['currant'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="currant")
essential_wine_df['oak'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="oak")
essential_wine_df['complex'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="complex")
essential_wine_df['buttery'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="buttery")
essential_wine_df['herb'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="herb")
essential_wine_df['orange'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="orange")
essential_wine_df['flower'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="flower")
essential_wine_df['crisp'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="crisp")
essential_wine_df['toast'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="toast")
essential_wine_df['pineapple'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="pineapple")
essential_wine_df['peach'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="peach")
essential_wine_df['classic'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="classic")
essential_wine_df['noble'] = conditional_column(dataframe=essential_wine_df, column="description", keyword="noble")

# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

country                                        description  points  price  \
4       US  Much like the regular bottling from 2012, this...      87     65   
10      US  Soft, supple plum envelopes an oaky structure ...      87     19   
12      US  Slightly reduced, this wine offers a chalky, t...      87     34   
14      US  Building on 150 years and six generations of w...      87     12   
21      US  A sleek mix of tart berry, stem and herb, alon...      87     20   

                                                title             variety  \
4   Sweet Cheeks 2012 Vintner's Reserve Wild Child...          Pinot Noir   
10  Kirkland Signature 2011 Mountain Cuvée Caberne...  Cabernet Sauvignon   
12  Louis M. Martini 2012 Cabernet Sauvignon (Alex...  Cabernet Sauvignon   
14           Mirassou 2012 Chardonnay (Central Coast)          Chardonnay   
21                   Acrobat 2013 Pinot Noir (Oregon)          Pinot Noir   

    vanilla  currant  oak  complex  buttery  herb  orange  flower  crisp  \
4         0        0    0        0        0     1       0       0      0   
10        0        0    1        0        0     0       0       0      0   
12        0        0    1        0        0     0       0       0      0   
14        0        0    0        0        0     0       0       0      0   
21        0        0    1        0        0     1       0       0      0   

    toast  pineapple  peach  classic  noble  
4       0          0      0        0      0  
10      0          0      0        0      0  
12      0          0      0        0      0  
14      0          1      0        1      0  
21      0          0      0        0      0

In [20]:
 #Drop the following column(s) from the dataframe
# 'description'
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.drop(['description'],axis = 1)

In [21]:
# Print the columns of data from the essential_wine_df dataframe
list(essential_wine_df)

['country',
 'points',
 'price',
 'title',
 'variety',
 'vanilla',
 'currant',
 'oak',
 'complex',
 'buttery',
 'herb',
 'orange',
 'flower',
 'crisp',
 'toast',
 'pineapple',
 'peach',
 'classic',
 'noble']

In [22]:
# One hot encode the 'country' column using the 'essential_wine_df' dataframe
# Assign the resulting matrix into a variable named "country_ohe_df"
country_ohe_df = pd.get_dummies(essential_wine_df[['country']],columns = ['country'])

In [24]:
 #Print the top 5 rows of data from the country_ohe_df dataframe
country_ohe_df.head(5)

country_Argentina  country_Australia  country_Austria  country_Brazil  \
4                   0                  0                0               0   
10                  0                  0                0               0   
12                  0                  0                0               0   
14                  0                  0                0               0   
21                  0                  0                0               0   

    country_Bulgaria  country_Canada  country_Chile  country_Croatia  \
4                  0               0              0                0   
10                 0               0              0                0   
12                 0               0              0                0   
14                 0               0              0                0   
21                 0               0              0                0   

    country_England  country_France       ...         country_Portugal  \
4                 0               0       ...                        0   
10                0               0       ...                        0   
12                0               0       ...                        0   
14                0               0       ...                        0   
21                0               0       ...                        0   

    country_Romania  country_Slovenia  country_South Africa  country_Spain  \
4                 0                 0                     0              0   
10                0                 0                     0              0   
12                0                 0                     0              0   
14                0                 0                     0              0   
21                0                 0                     0              0   

    country_Switzerland  country_Turkey  country_US  country_Ukraine  \
4                     0               0           1                0   
10                    0               0           1                0   
12                    0               0           1                0   
14                    0               0           1                0   
21                    0               0           1                0   

    country_Uruguay  
4                 0  
10                0  
12                0  
14                0  
21                0  

[5 rows x 32 columns]

In [25]:
# Join the 'country_ohe_df' to the 'essential_wine_df' dataframe
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = pd.concat([country_ohe_df, essential_wine_df],axis =1)

In [26]:
# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

country_Argentina  country_Australia  country_Austria  country_Brazil  \
4                   0                  0                0               0   
10                  0                  0                0               0   
12                  0                  0                0               0   
14                  0                  0                0               0   
21                  0                  0                0               0   

    country_Bulgaria  country_Canada  country_Chile  country_Croatia  \
4                  0               0              0                0   
10                 0               0              0                0   
12                 0               0              0                0   
14                 0               0              0                0   
21                 0               0              0                0   

    country_England  country_France  ...    buttery  herb  orange  flower  \
4                 0               0  ...          0     1       0       0   
10                0               0  ...          0     0       0       0   
12                0               0  ...          0     0       0       0   
14                0               0  ...          0     0       0       0   
21                0               0  ...          0     1       0       0   

    crisp  toast  pineapple  peach  classic  noble  
4       0      0          0      0        0      0  
10      0      0          0      0        0      0  
12      0      0          0      0        0      0  
14      0      0          1      0        1      0  
21      0      0          0      0        0      0  

[5 rows x 51 columns]

In [27]:
# Drop the following column(s) from the dataframe
# 'country'
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.drop(['country'],axis =1)

In [28]:
# Print the columns of data from the essential_wine_df dataframe
list(essential_wine_df)

['country_Argentina',
 'country_Australia',
 'country_Austria',
 'country_Brazil',
 'country_Bulgaria',
 'country_Canada',
 'country_Chile',
 'country_Croatia',
 'country_England',
 'country_France',
 'country_Germany',
 'country_Greece',
 'country_Hungary',
 'country_Israel',
 'country_Italy',
 'country_Lebanon',
 'country_Macedonia',
 'country_Mexico',
 'country_Moldova',
 'country_Morocco',
 'country_New Zealand',
 'country_Peru',
 'country_Portugal',
 'country_Romania',
 'country_Slovenia',
 'country_South Africa',
 'country_Spain',
 'country_Switzerland',
 'country_Turkey',
 'country_US',
 'country_Ukraine',
 'country_Uruguay',
 'points',
 'price',
 'title',
 'variety',
 'vanilla',
 'currant',
 'oak',
 'complex',
 'buttery',
 'herb',
 'orange',
 'flower',
 'crisp',
 'toast',
 'pineapple',
 'peach',
 'classic',
 'noble']

In [29]:
# One hot encode the 'variety' column using the 'essential_wine_df' dataframe
# Assign the resulting matrix into a variable named "variety_ohe_df"
variety_ohe_df = pd.get_dummies(essential_wine_df[['variety']],columns = ['variety'])

In [30]:
# Print the top 5 rows of data from the variety_ohe_df dataframe
variety_ohe_df.head(5)

variety_Cabernet Sauvignon  variety_Chardonnay  variety_Merlot  \
4                            0                   0               0   
10                           1                   0               0   
12                           1                   0               0   
14                           0                   1               0   
21                           0                   0               0   

    variety_Pinot Noir  variety_White Riesling  
4                    1                       0  
10                   0                       0  
12                   0                       0  
14                   0                       0  
21                   1                       0

In [31]:
# Join the 'variety_ohe_df' to the 'essential_wine_df' dataframe
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = pd.concat([variety_ohe_df, essential_wine_df],axis =1)

In [32]:
# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

variety_Cabernet Sauvignon  variety_Chardonnay  variety_Merlot  \
4                            0                   0               0   
10                           1                   0               0   
12                           1                   0               0   
14                           0                   1               0   
21                           0                   0               0   

    variety_Pinot Noir  variety_White Riesling  country_Argentina  \
4                    1                       0                  0   
10                   0                       0                  0   
12                   0                       0                  0   
14                   0                       0                  0   
21                   1                       0                  0   

    country_Australia  country_Austria  country_Brazil  country_Bulgaria  \
4                   0                0               0                 0   
10                  0                0               0                 0   
12                  0                0               0                 0   
14                  0                0               0                 0   
21                  0                0               0                 0   

    ...    buttery  herb  orange  flower  crisp  toast  pineapple  peach  \
4   ...          0     1       0       0      0      0          0      0   
10  ...          0     0       0       0      0      0          0      0   
12  ...          0     0       0       0      0      0          0      0   
14  ...          0     0       0       0      0      0          1      0   
21  ...          0     1       0       0      0      0          0      0   

    classic  noble  
4         0      0  
10        0      0  
12        0      0  
14        1      0  
21        0      0  

[5 rows x 55 columns]

In [33]:
# Drop the following column(s) from the dataframe
# 'variety'
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.drop(['variety'],axis =1)

In [34]:
# Print the columns of data from the essential_wine_df dataframe
list(essential_wine_df)


['variety_Cabernet Sauvignon',
 'variety_Chardonnay',
 'variety_Merlot',
 'variety_Pinot Noir',
 'variety_White Riesling',
 'country_Argentina',
 'country_Australia',
 'country_Austria',
 'country_Brazil',
 'country_Bulgaria',
 'country_Canada',
 'country_Chile',
 'country_Croatia',
 'country_England',
 'country_France',
 'country_Germany',
 'country_Greece',
 'country_Hungary',
 'country_Israel',
 'country_Italy',
 'country_Lebanon',
 'country_Macedonia',
 'country_Mexico',
 'country_Moldova',
 'country_Morocco',
 'country_New Zealand',
 'country_Peru',
 'country_Portugal',
 'country_Romania',
 'country_Slovenia',
 'country_South Africa',
 'country_Spain',
 'country_Switzerland',
 'country_Turkey',
 'country_US',
 'country_Ukraine',
 'country_Uruguay',
 'points',
 'price',
 'title',
 'vanilla',
 'currant',
 'oak',
 'complex',
 'buttery',
 'herb',
 'orange',
 'flower',
 'crisp',
 'toast',
 'pineapple',
 'peach',
 'classic',
 'noble']

In [35]:
# Using the 'essential_wine_df', sort the column 'title' by ascending order
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df =  essential_wine_df.sort_values(by = ['title'],ascending = True)

In [36]:
# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

variety_Cabernet Sauvignon  variety_Chardonnay  variety_Merlot  \
63807                            1                   0               0   
40994                            0                   1               0   
105674                           0                   0               0   
105683                           0                   1               0   
63346                            0                   0               0   

        variety_Pinot Noir  variety_White Riesling  country_Argentina  \
63807                    0                       0                  0   
40994                    0                       0                  0   
105674                   1                       0                  0   
105683                   0                       0                  0   
63346                    1                       0                  0   

        country_Australia  country_Austria  country_Brazil  country_Bulgaria  \
63807                   0                0               0                 0   
40994                   0                0               0                 0   
105674                  0                0               0                 0   
105683                  0                0               0                 0   
63346                   0                0               0                 0   

        ...    buttery  herb  orange  flower  crisp  toast  pineapple  peach  \
63807   ...          0     0       0       0      0      0          0      0   
40994   ...          0     0       0       0      0      0          1      0   
105674  ...          0     0       0       0      0      0          0      0   
105683  ...          0     0       0       0      0      0          0      0   
63346   ...          0     0       0       0      0      0          0      0   

        classic  noble  
63807         0      0  
40994         0      0  
105674        0      0  
105683        0      0  
63346         0      0  

[5 rows x 54 columns]

In [37]:
# Remove any rows from the dataframe which contain duplicate values using the subset column 'title'.
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.drop_duplicates(subset = ['title'])

In [38]:
# Print the size of the dataframe
essential_wine_df.shape

(33532, 54)

In [39]:
# Using the 'essential_wine_df', reset the dataframe index
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.reset_index(drop = True)

In [41]:
# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

variety_Cabernet Sauvignon  variety_Chardonnay  variety_Merlot  \
0                           1                   0               0   
1                           0                   1               0   
2                           0                   0               0   
3                           0                   1               0   
4                           0                   0               0   

   variety_Pinot Noir  variety_White Riesling  country_Argentina  \
0                   0                       0                  0   
1                   0                       0                  0   
2                   1                       0                  0   
3                   0                       0                  0   
4                   1                       0                  0   

   country_Australia  country_Austria  country_Brazil  country_Bulgaria  \
0                  0                0               0                 0   
1                  0                0               0                 0   
2                  0                0               0                 0   
3                  0                0               0                 0   
4                  0                0               0                 0   

   ...    buttery  herb  orange  flower  crisp  toast  pineapple  peach  \
0  ...          0     0       0       0      0      0          0      0   
1  ...          0     0       0       0      0      0          1      0   
2  ...          0     0       0       0      0      0          0      0   
3  ...          0     0       0       0      0      0          0      0   
4  ...          0     0       0       0      0      0          0      0   

   classic  noble  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      0  

[5 rows x 54 columns]

In [43]:

# Using SKLearn's Label Encoder Library, Instantiate the Label Encoder
# Assign the resulting object into a variable named "label_encoder"
label_encoder = LabelEncoder()



In [44]:
# Using the 'essential_wine_df', Fit the Label Encoder to the 'title' column
# Assign the resulting object into a variable named "label_encoder_fitted"
label_encoder_fitted = label_encoder.fit(essential_wine_df['title'])

In [45]:
# Using the 'essential_wine_df', Transform the Label Encoder to the 'title' column
# Assign the resulting object into a variable named "label_encoder_transformed"
label_encoder_transformed = label_encoder.fit_transform(essential_wine_df['title'])

In [46]:
# Create a Pandas DataFrame with a column name of 'title_encoded' and values of 'the variable label_encoder_transformed'
# Assign the resulting object into a variable named "title_encoded_df"
title_encoded_df = pd.DataFrame(data = label_encoder_transformed,columns = ['title_encoded'])


In [47]:
# Print the top 5 rows of data from the title_encoded_df dataframe
title_encoded_df.head(5)

title_encoded
0              0
1              1
2              2
3              3
4              4

In [48]:
# Join the 'title_encoded_df' to the 'essential_wine_df' dataframe
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = pd.concat([title_encoded_df,essential_wine_df],axis =1)


In [49]:
# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

title_encoded  variety_Cabernet Sauvignon  variety_Chardonnay  \
0              0                           1                   0   
1              1                           0                   1   
2              2                           0                   0   
3              3                           0                   1   
4              4                           0                   0   

   variety_Merlot  variety_Pinot Noir  variety_White Riesling  \
0               0                   0                       0   
1               0                   0                       0   
2               0                   1                       0   
3               0                   0                       0   
4               0                   1                       0   

   country_Argentina  country_Australia  country_Austria  country_Brazil  \
0                  0                  0                0               0   
1                  0                  0                0               0   
2                  0                  0                0               0   
3                  0                  0                0               0   
4                  0                  0                0               0   

   ...    buttery  herb  orange  flower  crisp  toast  pineapple  peach  \
0  ...          0     0       0       0      0      0          0      0   
1  ...          0     0       0       0      0      0          1      0   
2  ...          0     0       0       0      0      0          0      0   
3  ...          0     0       0       0      0      0          0      0   
4  ...          0     0       0       0      0      0          0      0   

   classic  noble  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      0  

[5 rows x 55 columns]

In [50]:
# Drop the following column(s) from the dataframe
# 'title'
# Assign the resulting matrix into a variable named "essential_wine_df"
essential_wine_df = essential_wine_df.drop(['title'],axis =1)

In [51]:
#Print the columns of data from the essential_wine_df dataframe
list(essential_wine_df)

['title_encoded',
 'variety_Cabernet Sauvignon',
 'variety_Chardonnay',
 'variety_Merlot',
 'variety_Pinot Noir',
 'variety_White Riesling',
 'country_Argentina',
 'country_Australia',
 'country_Austria',
 'country_Brazil',
 'country_Bulgaria',
 'country_Canada',
 'country_Chile',
 'country_Croatia',
 'country_England',
 'country_France',
 'country_Germany',
 'country_Greece',
 'country_Hungary',
 'country_Israel',
 'country_Italy',
 'country_Lebanon',
 'country_Macedonia',
 'country_Mexico',
 'country_Moldova',
 'country_Morocco',
 'country_New Zealand',
 'country_Peru',
 'country_Portugal',
 'country_Romania',
 'country_Slovenia',
 'country_South Africa',
 'country_Spain',
 'country_Switzerland',
 'country_Turkey',
 'country_US',
 'country_Ukraine',
 'country_Uruguay',
 'points',
 'price',
 'vanilla',
 'currant',
 'oak',
 'complex',
 'buttery',
 'herb',
 'orange',
 'flower',
 'crisp',
 'toast',
 'pineapple',
 'peach',
 'classic',
 'noble']

In [52]:
#Apply the 'to_numeric' function to the 'essential_wine_df'
# Assign the resulting matrix into a variable named "essential_wine_df"
cols = essential_wine_df.columns 
essential_wine_df[cols] = essential_wine_df[cols].apply(pd.to_numeric,errors = 'coerce') 

# Print the top 5 rows of data from the essential_wine_df dataframe
essential_wine_df.head(5)

title_encoded  variety_Cabernet Sauvignon  variety_Chardonnay  \
0              0                           1                   0   
1              1                           0                   1   
2              2                           0                   0   
3              3                           0                   1   
4              4                           0                   0   

   variety_Merlot  variety_Pinot Noir  variety_White Riesling  \
0               0                   0                       0   
1               0                   0                       0   
2               0                   1                       0   
3               0                   0                       0   
4               0                   1                       0   

   country_Argentina  country_Australia  country_Austria  country_Brazil  \
0                  0                  0                0               0   
1                  0                  0                0               0   
2                  0                  0                0               0   
3                  0                  0                0               0   
4                  0                  0                0               0   

   ...    buttery  herb  orange  flower  crisp  toast  pineapple  peach  \
0  ...          0     0       0       0      0      0          0      0   
1  ...          0     0       0       0      0      0          1      0   
2  ...          0     0       0       0      0      0          0      0   
3  ...          0     0       0       0      0      0          0      0   
4  ...          0     0       0       0      0      0          0      0   

   classic  noble  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      0  

[5 rows x 54 columns]

Splitting the data into training and test sets 

In [53]:
# Create a Numpy array for every column that is not 'title_encoded' (features)
# Assign the resulting matrix into a variable named "X"
X = essential_wine_df.iloc[:,1:].values

# Print the top 5 rows of data from the X dataframe
print(X[0:5,:])

# Create a Numpy array for the column 'title_encoded' (label)
# Assign the resulting matrix into a variable named "y"
y = essential_wine_df.iloc[:,0].values

# Print the top 5 rows of data from the y dataframe
print(y[0:5])

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  1  0  0  0  0  0 82 18  0  0  0  0  0  0  0  0  0
   0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  1  0  0 85 21  0  0  0  0  0  0  0  0  0
   0  1  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  1  0  0 83 15  0  0  0  0  0  0  0  0  0
   0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  1  0  0 83 13  0  0  1  0  0  0  0  0  0
   0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  1  0  0 83  7  0  0  0  0  0  0  0  0  0
   0  0  0  0  0]]
[0 1 2 3 4]


In [54]:
# Train, Test, and Split your Numpy array data sets (features and label)
# Used a test size of 0.001
# Used a random state of 42
# Assigned the resulting matrix into four variables named "X_train, X_test, y_train, y_test"
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.001,random_state = 42)

print(X_train, X_test, y_train, y_test)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]] [ 1520  2554 30975 ... 11284   860 15795] [  926 22954 14351  2929 25252 30170 21403 30144 32615  8278 16853 14843
 16302 20525 29602 26030 10493 19635 14575 27989  1448 18500   566 30135
 13706 24720 15041 17777 14277  7255  5436 23506 18651 12868]


In [55]:
# Instantiate the Decision Tree Classifier Model
# Use a random state of 42
# Use a max depth of 10
# Assign the resulting matrix into four variables named "model"
model = DecisionTreeClassifier(random_state = 42, max_depth =10)

# TODO: Print the Model Statistics
print(model)

# TODO: Fit your Training Data to the Decision Tree Classifier Model
# Assign the resulting matrix into four variables named "model"
model = model.fit(X_train,y_train)

def predict_top_five_wines(feature_preds):
    top_five_pred_list = []
    number_one_pred = model.predict(feature_preds)
    number_one_pred_name = label_encoder.inverse_transform(number_one_pred)
    top_five_pred_list.append(number_one_pred_name[0])
    top_four = np.argsort(model.predict_proba(feature_preds), axis=1)[0][-4:][::-1]
    for each_wine in top_four:
        top_four_wine_name = label_encoder.inverse_transform(each_wine)
        top_five_pred_list.append(top_four_wine_name)
    return top_five_pred_list

class BeOurGuest:
    def __init__(self, points, price, vanilla, currant, oak, complex, buttery, herb, orange, flower, crisp, toast,
                 pineapple, peach, classic, noble, argentina, australia, austria, brazil, bulgaria, canada, chile,
                 croatia, england, france, germany, greece, hungary, israel, italy, lebanon, macedonia, mexico,
                 moldova, morocco, new_zealand, peru, portugal, romania, slovenia, south_africa, spain,
                 switzerland, turkey, us, ukraine, uruguay, cabernet_sauvignon, chardonnay, merlot, pinot_noir,
                 white_riesling):
        self.points = points
        self.price = price
        self.vanilla = vanilla
        self.currant = currant
        self.oak = oak
        self.complex = complex
        self.buttery = buttery
        self.herb = herb
        self.orange = orange
        self.flower = flower
        self.crisp = crisp
        self.toast = toast
        self.pineapple = pineapple
        self.peach = peach
        self.classic = classic
        self.noble = noble
        self.argentina = argentina
        self.australia = australia
        self.austria = austria
        self.brazil = brazil
        self.bulgaria = bulgaria
        self.canada = canada
        self.chile = chile
        self.croatia = croatia
        self.england = england
        self.france = france
        self.germany = germany
        self.greece = greece
        self.hungary = hungary
        self.israel = israel
        self.italy = italy
        self.lebanon = lebanon
        self.macedonia = macedonia
        self.mexico = mexico
        self.moldova = moldova
        self.morocco = morocco
        self.new_zealand = new_zealand
        self.peru = peru
        self.portugal = portugal
        self.romania = romania
        self.slovenia = slovenia
        self.south_africa = south_africa
        self.spain = spain
        self.switzerland = switzerland
        self.turkey = turkey
        self.us = us
        self.ukraine = ukraine
        self.uruguay = uruguay
        self.cabernet_sauvignon = cabernet_sauvignon
        self.chardonnay = chardonnay
        self.merlot = merlot
        self.pinot_noir = pinot_noir
        self.white_riesling = white_riesling

    def wine_pref_params(self):
        return [[self.points, self.price, self.vanilla, self.currant, self.oak, self.complex, self.buttery, self.herb, self.orange,
                 self.flower, self.crisp, self.toast, self.pineapple, self.peach, self.classic, self.noble,
                 self.argentina, self.australia, self.austria, self.brazil, self.bulgaria, self.canada, self.chile, self.croatia,
                 self.england, self.france, self.germany, self.greece, self.hungary, self.israel, self.italy, self.lebanon, self.macedonia,
                 self.mexico, self.moldova, self.morocco, self.new_zealand, self.peru, self.portugal, self.romania, self.slovenia, self.south_africa,
                 self.spain, self.switzerland, self.turkey, self.us, self.ukraine, self.uruguay, self.cabernet_sauvignon, self.chardonnay,
                 self.merlot, self.pinot_noir, self.white_riesling ]]

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=42, splitter='best')


select the appropriate value for the guest list 

In [56]:
patty_jenkins = BeOurGuest(
    points=92,
    price = 50,
    vanilla = 1,
    currant = 1,
    oak = 1,
    complex = 1,
    buttery = 0,
    herb = 0,
    orange = 0,
    flower = 0,
    crisp = 0,
    toast = 0,
    pineapple = 0,
    peach = 0,
    classic = 0,
    noble = 0,
    argentina = 0,
    australia = 0,
    austria = 0,
    brazil = 0,
    bulgaria = 0,
    canada = 0,
    chile = 0,
    croatia = 0,
    england = 0,
    france = 0,
    germany = 0,
    greece = 0,
    hungary = 0,
    israel = 0,
    italy = 0,
    lebanon = 0,
    macedonia = 0,
    mexico = 0,
    moldova = 0,
    morocco = 0,
    new_zealand = 0,
    peru = 0,
    portugal = 0,
    romania = 0,
    slovenia = 0,
    south_africa = 0,
    spain = 0,
    switzerland = 0,
    turkey = 0,
    us = 1,
    ukraine = 0,
    uruguay = 0,
    cabernet_sauvignon = 1,
    chardonnay = 0,
    merlot = 0,
    pinot_noir = 0,
    white_riesling = 0,
)

george_mcfly = BeOurGuest(
    points=90,
    price = 40,
    vanilla = 0,
    currant = 0,
    oak = 0,
    complex = 0,
    buttery = 1,
    herb = 0,
    orange = 0,
    flower = 0,
    crisp = 0,
    toast = 0,
    pineapple = 0,
    peach = 0,
    classic = 0,
    noble = 0,
    argentina = 0,
    australia = 0,
    austria = 0,
    brazil = 0,
    bulgaria = 0,
    canada = 0,
    chile = 0,
    croatia = 0,
    england = 0,
    france = 0,
    germany = 0,
    greece = 0,
    hungary = 0,
    israel = 0,
    italy = 0,
    lebanon = 0,
    macedonia = 0,
    mexico = 0,
    moldova = 0,
    morocco = 0,
    new_zealand = 0,
    peru = 0,
    portugal = 0,
    romania = 0,
    slovenia = 0,
    south_africa = 0,
    spain = 0,
    switzerland = 0,
    turkey = 0,
    us = 1,
    ukraine = 0,
    uruguay = 0,
    cabernet_sauvignon = 0,
    chardonnay = 0,
    merlot = 0,
    pinot_noir = 1,
    white_riesling = 0,
)

dr_jerilynn_prior = BeOurGuest(
    points=95,
    price = 30,
    vanilla = 1,
    currant = 0,
    oak = 1,
    complex = 0,
    buttery = 0,
    herb = 1,
    orange = 0,
    flower = 0,
    crisp = 0,
    toast = 0,
    pineapple = 0,
    peach = 0,
    classic = 0,
    noble = 0,
    argentina = 0,
    australia = 0,
    austria = 0,
    brazil = 0,
    bulgaria = 0,
    canada = 0,
    chile = 0,
    croatia = 0,
    england = 0,
    france = 0,
    germany = 0,
    greece = 0,
    hungary = 0,
    israel = 0,
    italy = 0,
    lebanon = 0,
    macedonia = 0,
    mexico = 0,
    moldova = 0,
    morocco = 0,
    new_zealand = 0,
    peru = 0,
    portugal = 0,
    romania = 0,
    slovenia = 0,
    south_africa = 0,
    spain = 0,
    switzerland = 0,
    turkey = 0,
    us = 1,
    ukraine = 0,
    uruguay = 0,
    cabernet_sauvignon = 0,
    chardonnay = 0,
    merlot = 0,
    pinot_noir = 1,
    white_riesling = 0,
)

dr_henry_jones_jr = BeOurGuest(
    points=80,
    price = 20,
    vanilla = 0,
    currant = 0,
    oak = 0,
    complex = 0,
    buttery = 0,
    herb = 0,
    orange = 1,
    flower = 0,
    crisp = 1,
    toast = 0,
    pineapple = 0,
    peach = 1,
    classic = 1,
    noble = 1,
    argentina = 0,
    australia = 0,
    austria = 0,
    brazil = 0,
    bulgaria = 0,
    canada = 0,
    chile = 0,
    croatia = 0,
    england = 0,
    france = 0,
    germany = 0,
    greece = 0,
    hungary = 0,
    israel = 0,
    italy = 1,
    lebanon = 0,
    macedonia = 0,
    mexico = 0,
    moldova = 0,
    morocco = 0,
    new_zealand = 0,
    peru = 0,
    portugal = 0,
    romania = 0,
    slovenia = 0,
    south_africa = 0,
    spain = 0,
    switzerland = 0,
    turkey = 0,
    us = 0,
    ukraine = 0,
    uruguay = 0,
    cabernet_sauvignon = 0,
    chardonnay = 1,
    merlot = 0,
    pinot_noir = 0,
    white_riesling = 0,
)

michael_mick_dundee = BeOurGuest(
    points=90,
    price = 60,
    vanilla = 0,
    currant = 0,
    oak = 1,
    complex = 0,
    buttery = 1,
    herb = 0,
    orange = 0,
    flower = 0,
    crisp = 0,
    toast = 1,
    pineapple = 1,
    peach = 1,
    classic = 0,
    noble = 0,
    argentina = 0,
    australia = 0,
    austria = 0,
    brazil = 0,
    bulgaria = 0,
    canada = 0,
    chile = 0,
    croatia = 0,
    england = 0,
    france = 0,
    germany = 0,
    greece = 0,
    hungary = 0,
    israel = 0,
    italy = 0,
    lebanon = 0,
    macedonia = 0,
    mexico = 0,
    moldova = 0,
    morocco = 0,
    new_zealand = 0,
    peru = 0,
    portugal = 0,
    romania = 0,
    slovenia = 0,
    south_africa = 0,
    spain = 0,
    switzerland = 0,
    turkey = 0,
    us = 1,
    ukraine = 0,
    uruguay = 0,
    cabernet_sauvignon = 0,
    chardonnay = 0,
    merlot = 1,
    pinot_noir = 0,
    white_riesling = 0,
)

print(f'Each Guest has been assigned a wine!')

Each Guest has been assigned a wine!


In [57]:
#  Call the function 'wine_pref_params' for each guest within the Class 'BeOurGuest'
# Assign the result into a variable named "guest_one_wine_pred_nest_arr"
guest_one_wine_pred_nest_arr = patty_jenkins.wine_pref_params()
guest_two_wine_pred_nest_arr = george_mcfly.wine_pref_params()
guest_three_wine_pred_nest_arr = dr_jerilynn_prior.wine_pref_params()
guest_four_wine_pred_nest_arr = dr_henry_jones_jr.wine_pref_params()
guest_five_wine_pred_nest_arr =michael_mick_dundee.wine_pref_params()

In [58]:
# Call the 'predict_top_five_wines' function for each guest
# Use 'guest_one_wine_pred_nest_arr' for the function argument
# Assign the result into a variable named "guest_pred_one"
guest_pred_one = predict_top_five_wines(guest_one_wine_pred_nest_arr)
guest_pred_two = predict_top_five_wines(guest_two_wine_pred_nest_arr)
guest_pred_three = predict_top_five_wines(guest_three_wine_pred_nest_arr)
guest_pred_four = predict_top_five_wines(guest_four_wine_pred_nest_arr)
guest_pred_five = predict_top_five_wines(guest_five_wine_pred_nest_arr)

In [59]:
#Create a dictionary using the guest number as the key and the list of predictions for each guest as the values
# Assign the result into a variable named "compiled_wine_dictionary"
compiled_wine_dictionary = {
    'one':guest_pred_one,
    'two' :guest_pred_two,
    'three' :guest_pred_three,
    'four' :guest_pred_four,
    'five' :guest_pred_five
}

# BooM !!! Here is your prediction of top 5 wines for each of the client. 

In [60]:
print(compiled_wine_dictionary)

{'one': ['Acacia 2013 Winery Lake Vineyard Estate Grown Pinot Noir (Carneros)', 'Au Bon Climat 2008 Sanford & Benedict Vineyard Chardonnay (Santa Ynez Valley)', 'Anaba 2012 Las Brisas Vineyard Pinot Noir (Carneros)', 'Renteria 2011 Cabernet Sauvignon (Napa Valley)', 'Willamette Valley Vineyards 2010 Tualatin Estate Pinot Noir (Willamette Valley)'], 'two': ['Brion 2003 Cabernet Sauvignon (Napa Valley)', 'HKG 2009 Bridge Selection Pinot Noir (Russian River Valley)', 'Iron Hub 2014 Small Lot Chardonnay (Sierra Foothills)', 'Tsillan Cellars 2006 Estate-Barrel Select Chardonnay (Columbia Valley (WA))', 'Jenica Peak 2011 Coastal Series Chardonnay (California)'], 'three': ['Brion 2003 Cabernet Sauvignon (Napa Valley)', 'HKG 2009 Bridge Selection Pinot Noir (Russian River Valley)', 'Iron Hub 2014 Small Lot Chardonnay (Sierra Foothills)', 'Tsillan Cellars 2006 Estate-Barrel Select Chardonnay (Columbia Valley (WA))', 'Jenica Peak 2011 Coastal Series Chardonnay (California)'], 'four': ["Quails' G

In [61]:
# Assign the result into a variable named "compiled_wine_dictionary"
final_wine_choices_df = pd.DataFrame.from_dict(compiled_wine_dictionary)

# TODO: Print the final_wine_choices_dataframe
print(final_wine_choices_df)

                                                 one  \
0  Acacia 2013 Winery Lake Vineyard Estate Grown ...   
1  Au Bon Climat 2008 Sanford & Benedict Vineyard...   
2  Anaba 2012 Las Brisas Vineyard Pinot Noir (Car...   
3     Renteria 2011 Cabernet Sauvignon (Napa Valley)   
4  Willamette Valley Vineyards 2010 Tualatin Esta...   

                                                 two  \
0        Brion 2003 Cabernet Sauvignon (Napa Valley)   
1  HKG 2009 Bridge Selection Pinot Noir (Russian ...   
2  Iron Hub 2014 Small Lot Chardonnay (Sierra Foo...   
3  Tsillan Cellars 2006 Estate-Barrel Select Char...   
4  Jenica Peak 2011 Coastal Series Chardonnay (Ca...   

                                               three  \
0        Brion 2003 Cabernet Sauvignon (Napa Valley)   
1  HKG 2009 Bridge Selection Pinot Noir (Russian ...   
2  Iron Hub 2014 Small Lot Chardonnay (Sierra Foo...   
3  Tsillan Cellars 2006 Estate-Barrel Select Char...   
4  Jenica Peak 2011 Coastal Series Chardonnay 